### PR TITLE
add support for cforest

### PR DESCRIPTION
**Pull request by sumny**
some open points:
`cforest`:
- `importance` method currently commented (may need a bugfix in `partykit`, WIP)
- should the parameters for `importance` be also set up in the `param_set`, see all arguments for `partykit::varimp`? If not, should the arguments be checked via `checkmate`? (I guess so)
- what is the current state of `strata` handling in `mlr3`, is this already supported in general?

### CODE REVIEW

**Comment by be-marc** [comment]
We only use the parameter set tags to differentiate between `train`, `predict` and `importance`. If you need to split the parameter set for the `.train` method, you can use

``` 
pars_control = pars[which(names(pars) %in%  formalArgs(partykit::ctree_control))] 
```

Nice work!

**Review by pat-s — COMMENTED** [review]
Can we please split both learners if they are not so trivial and somewhat different?

Also pkease style the files according to our [mlr-style](https://github.com/mlr-org/mlr3/wiki/style-guide#styler-mlr-style). This includes breaking at 80 width.

> should the parameters for importance be also set up in the param_set

AFAIK we do not have learners with params for their importance method yet.
But as Marc said, tag them in the ParamSet.

What is the {sandwich} package for?

**Comment by sumny** [comment]
Thanks for your comments!

> Can we please split both learners if they are not so trivial and somewhat different?

I made a new branch for the `mob()` part, so this branch now only adds `cforest()`

> Also pkease style the files according to our [mlr-style](https://github.com/mlr-org/mlr3/wiki/style-guide#styler-mlr-style). This includes breaking at 80 width.

I guess I can do line breaks at 80 width, however, using the styler, this is not automatically applied (?) Also, almost all lines with the parameters would be spanned over two or three lines then. Imo this makes the code harder to read. Also I do not see most code files in `mlr3` adhering to the 80 line width?

> What is the {sandwich} package for?

partykit relies on sandwich for a robust estimation of the vcov during the tests for parameter instability. Actually it should not be needed to import it, but the tic checks failed earlier if I did not import it: https://github.com/mlr3learners/mlr3learners.partykit/runs/525996188#step:16:128 I'll remove it and try again

**Comment by pat-s** [comment]
> I guess I can do line breaks at 80 width, however, using the styler, this is not automatically applied (?) 

Correct, you need to do this yourself.

> Also, almost all lines with the parameters would be spanned over two or three lines then. Imo this makes the code harder to read. Also I do not see most code files in mlr3 adhering to the 80 line width?

We have somewhat different opinions on linebreaks within the team unfortunately.
One can discuss whether linebreaks or long lines make things harder to read - I think that everything above 100 is really annoying because most diff tools do not support that width (and I do not like horizontal scrolling).
The same applies for comments.

Once you are ready for review please mark the PR accordingly. Thanks!

**Comment by sumny** [comment]
@pat-s this is now ready for review (checklist passed and CI and paramtest as well; expect for macOS devel seems to be broken)

**Comment by pat-s** [comment]
Should these be mentioned in the help page of the learner?

```
      # set the cforest specific ctree_control parameters
      ps$values$teststat = "quadratic"
      ps$values$testtype = "Univariate"
      ps$values$mincriterion = 0
      ps$values$saveinfo = FALSE
```

>     "strata", # FIXME: handled in mlr3?

Yes.

---

Looks good!

**Comment by sumny** [comment]
> Should these be mentioned in the help page of the learner?
> 
> ```
>       # set the cforest specific ctree_control parameters
>       ps$values$teststat = "quadratic"
>       ps$values$testtype = "Univariate"
>       ps$values$mincriterion = 0
>       ps$values$saveinfo = FALSE
> ```

I do not think this is necessary because this does not differ from the defaults of `cforest` itself. It is just there because `cforest` internally calls `ctree_control` with different defaults than how `ctree_control` is normally called and therefore we also had to do this here.

**Pull request merged**
